package proyectojuegos;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import javax.swing.ImageIcon;

/**
 *
 * @author jenni
 */
public class JuegoPiscina extends javax.swing.JFrame {

    /**
     * Creates new form JuegoPiscina
     */
    public static boolean boton1= true;
    public JuegoPiscina() {

        initComponents();
    }

    public void detenerimagen() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nadador1 = new javax.swing.JLabel();
        nadador2 = new javax.swing.JLabel();
        nadador3 = new javax.swing.JLabel();
        nadador4 = new javax.swing.JLabel();
        nadador5 = new javax.swing.JLabel();
        nueva = new javax.swing.JButton();
        nada5 = new javax.swing.JButton();
        nada4 = new javax.swing.JButton();
        nada3 = new javax.swing.JButton();
        nada2 = new javax.swing.JButton();
        nada1 = new javax.swing.JButton();
        piscina = new javax.swing.JLabel();
        eliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtR = new javax.swing.JTextArea();
        iniciar = new javax.swing.JButton();
        lblLinea = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(nadador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 100, 100));
        getContentPane().add(nadador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 120, 90));
        getContentPane().add(nadador3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 100, 100));
        getContentPane().add(nadador4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 110, 90));
        getContentPane().add(nadador5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 120, 80));

        nueva.setText("Nueva");
        nueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevaActionPerformed(evt);
            }
        });
        getContentPane().add(nueva, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 140, 90, 40));

        nada5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/1.png"))); // NOI18N
        nada5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nada5ActionPerformed(evt);
            }
        });
        getContentPane().add(nada5, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 0, 60, 70));

        nada4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/2.png"))); // NOI18N
        nada4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nada4ActionPerformed(evt);
            }
        });
        getContentPane().add(nada4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, 60, 70));

        nada3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/3.png"))); // NOI18N
        nada3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nada3ActionPerformed(evt);
            }
        });
        getContentPane().add(nada3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, 60, 70));

        nada2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/4.png"))); // NOI18N
        nada2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nada2ActionPerformed(evt);
            }
        });
        getContentPane().add(nada2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 60, 70));

        nada1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/5.png"))); // NOI18N
        nada1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nada1ActionPerformed(evt);
            }
        });
        getContentPane().add(nada1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 60, 70));

        piscina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/piscina.png"))); // NOI18N
        getContentPane().add(piscina, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 860, 420));

        eliminar.setText("Eliminar Nadador");
        getContentPane().add(eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        txtR.setColumns(20);
        txtR.setRows(5);
        jScrollPane1.setViewportView(txtR);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 230, 180, 170));

        iniciar.setText("INICIAR CARRERA");
        iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarActionPerformed(evt);
            }
        });
        getContentPane().add(iniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 70, 140, 40));

        lblLinea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/linea.png"))); // NOI18N
        getContentPane().add(lblLinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 80, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nada3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nada3ActionPerformed
        // TODO add your handling code here:
        nada3.setEnabled(false);
        ImageIcon icono = new ImageIcon(getClass().getResource("/imagenes/1.png"));
        JuegoPiscina.nadador3.setIcon(icono);
    }//GEN-LAST:event_nada3ActionPerformed

    private void nada1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nada1ActionPerformed
        // TODO add your handling code here:
        nada1.setEnabled(false);
        ImageIcon icono = new ImageIcon(getClass().getResource("/imagenes/1.png"));
        JuegoPiscina.nadador1.setIcon(icono);
        boolean boton1 = false;
    }//GEN-LAST:event_nada1ActionPerformed

    private void nada2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nada2ActionPerformed
        // TODO add your handling code here:
        nada2.setEnabled(false);

        ImageIcon icono = new ImageIcon(getClass().getResource("/imagenes/1.png"));
        JuegoPiscina.nadador2.setIcon(icono);
    }//GEN-LAST:event_nada2ActionPerformed

    private void nada4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nada4ActionPerformed
        // TODO add your handling code here:
        nada4.setEnabled(false);
        ImageIcon icono = new ImageIcon(getClass().getResource("/imagenes/1.png"));
        JuegoPiscina.nadador4.setIcon(icono);
    }//GEN-LAST:event_nada4ActionPerformed

    private void nada5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nada5ActionPerformed
        // TODO add your handling code here:
        nada5.setEnabled(false);
        ImageIcon icono = new ImageIcon(getClass().getResource("/imagenes/1.png"));
        JuegoPiscina.nadador5.setIcon(icono);
    }//GEN-LAST:event_nada5ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        nueva.setEnabled(false);
        carrera.registrarNadador();
        nadador1.setText(carrera.losNadadores[0].getNombre());
    }//GEN-LAST:event_formWindowOpened

    private void nuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevaActionPerformed
        // TODO add your handling code here:
        carrera.reiniciar();
        nadador1.setLocation(carrera.losNadadores[0].getCoorX(), carrera.losNadadores[0].getCoorY());
        iniciar.setEnabled(true);
        nueva.setEnabled(false);
//        carrera.detener();

    }//GEN-LAST:event_nuevaActionPerformed

    private void iniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarActionPerformed
        // TODO add your handling code here:
        JuegoPiscina.txtR.setText("->");
        carrera.iniciar();
//        carrera.mover();
        iniciar.setEnabled(false);
        nueva.setEnabled(true);
    }//GEN-LAST:event_iniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JuegoPiscina.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JuegoPiscina().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton eliminar;
    private javax.swing.JButton iniciar;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JLabel lblLinea;
    private javax.swing.JButton nada1;
    private javax.swing.JButton nada2;
    private javax.swing.JButton nada3;
    private javax.swing.JButton nada4;
    private javax.swing.JButton nada5;
    public static javax.swing.JLabel nadador1;
    public static javax.swing.JLabel nadador2;
    public static javax.swing.JLabel nadador3;
    public static javax.swing.JLabel nadador4;
    public static javax.swing.JLabel nadador5;
    private javax.swing.JButton nueva;
    public static javax.swing.JLabel piscina;
    public static javax.swing.JTextArea txtR;
    // End of variables declaration//GEN-END:variables
}
