package proyectojuegos;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author jenni
 */
public class JuegoPiscina extends javax.swing.JFrame {

    /**
     * Creates new form JuegoPiscina
     */
    String n1 = "";
    String n2 = "";
    String n3 = "";
    String n4 = "";
    String n5 = "";
    boolean bus = false;
 
    public JuegoPiscina() {

        initComponents();
        back2.setBorder(null);
        back2.setContentAreaFilled(false);
        cerrar2.setBorder(null);
        cerrar2.setContentAreaFilled(false);
        nada1.setContentAreaFilled(false);
        nada1.setBorder(null);
        nada2.setContentAreaFilled(false);
        nada2.setBorder(null);
        nada3.setContentAreaFilled(false);
        nada3.setBorder(null);
        nada4.setContentAreaFilled(false);
        nada4.setBorder(null);
        nada5.setContentAreaFilled(false);
        nada5.setBorder(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eliminar = new javax.swing.JButton();
        back2 = new javax.swing.JButton();
        cerrar2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblLinea = new javax.swing.JLabel();
        nadador1 = new javax.swing.JLabel();
        nadador2 = new javax.swing.JLabel();
        nadador3 = new javax.swing.JLabel();
        nadador4 = new javax.swing.JLabel();
        nadador5 = new javax.swing.JLabel();
        piscina = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        nada1 = new javax.swing.JButton();
        nada2 = new javax.swing.JButton();
        nada3 = new javax.swing.JButton();
        nada4 = new javax.swing.JButton();
        nada5 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        iniciar = new javax.swing.JButton();
        nueva = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtR = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        eliminar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        eliminar.setText("Eliminar Nadador");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });
        getContentPane().add(eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        back2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/flecha-hacia-la-izquierda.png"))); // NOI18N
        back2.setFocusable(false);
        back2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back2ActionPerformed(evt);
            }
        });
        getContentPane().add(back2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 50, -1));

        cerrar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar.png"))); // NOI18N
        cerrar2.setFocusable(false);
        cerrar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrar2ActionPerformed(evt);
            }
        });
        getContentPane().add(cerrar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 10, 50, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(lblLinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 10, -1, 400));
        jPanel1.add(nadador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 110, 80));
        jPanel1.add(nadador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 110, 80));
        jPanel1.add(nadador3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 100, 80));
        jPanel1.add(nadador4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 100, 80));

        nadador5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nadador5MousePressed(evt);
            }
        });
        jPanel1.add(nadador5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 100, 70));

        piscina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/piscina.png"))); // NOI18N
        jPanel1.add(piscina, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 850, 420));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 860, 460));

        jPanel2.setBackground(new java.awt.Color(233, 150, 122));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Seleccione nadadores ");
        jPanel2.add(jLabel2);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/llave1.png"))); // NOI18N
        jPanel2.add(jLabel1);

        nada1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/5.png"))); // NOI18N
        nada1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nada1ActionPerformed(evt);
            }
        });
        jPanel2.add(nada1);

        nada2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/4.png"))); // NOI18N
        nada2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nada2ActionPerformed(evt);
            }
        });
        jPanel2.add(nada2);

        nada3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/3.png"))); // NOI18N
        nada3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nada3ActionPerformed(evt);
            }
        });
        jPanel2.add(nada3);

        nada4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/2.png"))); // NOI18N
        nada4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nada4ActionPerformed(evt);
            }
        });
        jPanel2.add(nada4);

        nada5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/1.png"))); // NOI18N
        nada5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nada5ActionPerformed(evt);
            }
        });
        jPanel2.add(nada5);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 10, -1, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        iniciar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        iniciar.setText("INICIAR CARRERA");
        iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarActionPerformed(evt);
            }
        });

        nueva.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        nueva.setText("NUEVA CARRERA");
        nueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevaActionPerformed(evt);
            }
        });

        txtR.setEditable(false);
        txtR.setColumns(20);
        txtR.setRows(5);
        jScrollPane1.setViewportView(txtR);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(nueva))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(iniciar)))
                .addGap(56, 56, 56))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(iniciar)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(nueva)
                .addContainerGap())
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 140, 230, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nada3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nada3ActionPerformed
        // TODO add your handling code here:
        nada3.setEnabled(false);
        ImageIcon icono = new ImageIcon(getClass().getResource("/imagenes/1.png"));
        JuegoPiscina.nadador3.setIcon(icono);
        bus = true;
        n3 = "3";
    }//GEN-LAST:event_nada3ActionPerformed

    private void nada1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nada1ActionPerformed
        // TODO add your handling code here:
        nada1.setEnabled(false);
        ImageIcon icono = new ImageIcon(getClass().getResource("/imagenes/1.png"));
        JuegoPiscina.nadador1.setIcon(icono);
        bus = true;
        n1 = "1";
    }//GEN-LAST:event_nada1ActionPerformed

    private void nada2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nada2ActionPerformed
        // TODO add your handling code here:
        nada2.setEnabled(false);
        ImageIcon icono = new ImageIcon(getClass().getResource("/imagenes/1.png"));
        JuegoPiscina.nadador2.setIcon(icono);
        bus = true;
        n2 = "2";
    }//GEN-LAST:event_nada2ActionPerformed

    private void nada4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nada4ActionPerformed
        // TODO add your handling code here:
        nada4.setEnabled(false);
        ImageIcon icono = new ImageIcon(getClass().getResource("/imagenes/1.png"));
        JuegoPiscina.nadador4.setIcon(icono);
        bus = true;
        n4 = "4";
    }//GEN-LAST:event_nada4ActionPerformed

    private void nada5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nada5ActionPerformed
        // TODO add your handling code here:
        nada5.setEnabled(false);
        ImageIcon icono = new ImageIcon(getClass().getResource("/imagenes/1.png"));
        JuegoPiscina.nadador5.setIcon(icono);
        bus = true;
        n5 = "5";
    }//GEN-LAST:event_nada5ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        nueva.setEnabled(false);
        carrera.registrarNadador();
    }//GEN-LAST:event_formWindowOpened

    private void nuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevaActionPerformed
        // TODO add your handling code here:
//        carrera.reiniciar();
//        nadador1.setLocation(carrera.losNadadores[0].getCoorX(), carrera.losNadadores[0].getCoorY());
//        nadador2.setLocation(carrera.losNadadores[1].getCoorX(), carrera.losNadadores[1].getCoorY());
//        nadador3.setLocation(carrera.losNadadores[2].getCoorX(), carrera.losNadadores[2].getCoorY());
//        nadador4.setLocation(carrera.losNadadores[3].getCoorX(), carrera.losNadadores[3].getCoorY());
//        nadador5.setLocation(carrera.losNadadores[4].getCoorX(), carrera.losNadadores[4].getCoorY());
        nadador1.setIcon(null);
        nadador2.setIcon(null);
        nadador3.setIcon(null);
        nadador4.setIcon(null);
        nadador5.setIcon(null);
        nada1.setEnabled(true);
        nada2.setEnabled(true);
        nada3.setEnabled(true);
        nada4.setEnabled(true);
        nada5.setEnabled(true);
        iniciar.setEnabled(true);
        nueva.setEnabled(false);
        bus = false;
        n1 = "";
        n2 = "";
        n3 = "";
        n4 = "";
        n5 = "";
    }//GEN-LAST:event_nuevaActionPerformed


    private void iniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarActionPerformed
        if (bus) {
            JuegoPiscina.txtR.setText("TIEMPO DE CADA NADADOR");
            carrera.iniciar(n1, n2, n3, n4, n5);
            iniciar.setEnabled(false);
            nueva.setEnabled(true);
            
        }
    }//GEN-LAST:event_iniciarActionPerformed

    private void back2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back2ActionPerformed
        // TODO add your handling code here:
        Juegos2 ventana = new Juegos2();
        ventana.setLocationRelativeTo(null);
        ventana.setVisible(true);
        ventana.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        dispose();
    }//GEN-LAST:event_back2ActionPerformed

    private void cerrar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrar2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_cerrar2ActionPerformed

    private void nadador5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nadador5MousePressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_nadador5MousePressed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_eliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JuegoPiscina.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JuegoPiscina().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back2;
    private javax.swing.JButton cerrar2;
    private javax.swing.JButton eliminar;
    private javax.swing.JButton iniciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JLabel lblLinea;
    private javax.swing.JButton nada1;
    private javax.swing.JButton nada2;
    private javax.swing.JButton nada3;
    private javax.swing.JButton nada4;
    private javax.swing.JButton nada5;
    public static javax.swing.JLabel nadador1;
    public static javax.swing.JLabel nadador2;
    public static javax.swing.JLabel nadador3;
    public static javax.swing.JLabel nadador4;
    public static javax.swing.JLabel nadador5;
    private javax.swing.JButton nueva;
    public static javax.swing.JLabel piscina;
    public static javax.swing.JTextArea txtR;
    // End of variables declaration//GEN-END:variables
}
